"""Add milestone flags

Revision ID: 0353ad8400a3
Revises: 67980a72852b
Create Date: 2026-01-13 19:28:57.505986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0353ad8400a3'
down_revision = '67980a72852b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestone_15_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('milestone_30_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('milestone_60_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('milestone_100_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('milestone_365_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('milestone_365_sent')
        batch_op.drop_column('milestone_100_sent')
        batch_op.drop_column('milestone_60_sent')
        batch_op.drop_column('milestone_30_sent')
        batch_op.drop_column('milestone_15_sent')

    # ### end Alembic commands ###
