"""Add Score model

Revision ID: 67980a72852b
Revises: 705c80684a49
Create Date: 2026-01-09 22:32:01.543944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67980a72852b'
down_revision = '705c80684a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('best_score', sa.Integer(), nullable=True),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    # ### end Alembic commands ###
