"""Allow announcements for all users

Revision ID: 705c80684a49
Revises: 7c62d2ab9252
Create Date: 2026-01-04 23:25:47.975776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705c80684a49'
down_revision = '7c62d2ab9252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
