"""add site reviews

Revision ID: ea8b211a6dfa
Revises: 0353ad8400a3
Create Date: 2026-01-15 18:57:28.869808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8b211a6dfa'
down_revision = '0353ad8400a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=120), nullable=True),
    sa.Column('contact_info', sa.String(length=120), nullable=True),
    sa.Column('appearance', sa.String(length=50), nullable=True),
    sa.Column('navigation', sa.String(length=50), nullable=True),
    sa.Column('speed', sa.String(length=50), nullable=True),
    sa.Column('utility', sa.String(length=50), nullable=True),
    sa.Column('recommend', sa.String(length=20), nullable=True),
    sa.Column('improve', sa.Text(), nullable=True),
    sa.Column('best_feature', sa.Text(), nullable=True),
    sa.Column('hard_feature', sa.Text(), nullable=True),
    sa.Column('contact_back', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('milestone_365_sent')
        batch_op.drop_column('milestone_60_sent')
        batch_op.drop_column('milestone_15_sent')
        batch_op.drop_column('milestone_30_sent')
        batch_op.drop_column('milestone_100_sent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestone_100_sent', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('milestone_30_sent', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('milestone_15_sent', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('milestone_60_sent', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('milestone_365_sent', sa.BOOLEAN(), nullable=True))

    op.drop_table('site_review')
    # ### end Alembic commands ###
